apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: MyApp
  template:
    metadata:
      labels:
        name: MyApp
    spec:
      serviceAccountName: MyApp
      containers:
        - name: MyApp
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - MyApp
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "MyApp"
