kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: MyApp
subjects:
- kind: ServiceAccount
  name: MyApp
roleRef:
  kind: Role
  name: MyApp
  apiGroup: rbac.authorization.k8s.io
