kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app
subjects:
- kind: ServiceAccount
  name: my-app
roleRef:
  kind: Role
  name: my-app
  apiGroup: rbac.authorization.k8s.io
