kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backuper
subjects:
- kind: ServiceAccount
  name: backuper
roleRef:
  kind: Role
  name: backuper
  apiGroup: rbac.authorization.k8s.io
