apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupers.bpaxio.edu
spec:
  group: bpaxio.edu
  names:
    kind: Backuper
    listKind: BackuperList
    plural: backupers
    singular: backuper
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Backuper is the Schema for the backupers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BackuperSpec defines the desired state of Backuper
          type: object
        status:
          description: BackuperStatus defines the observed state of Backuper
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
